const PERMISSIOM = require("./permission");

exports.ADMIN = {
  name: "Admin",
  permissions: [
    PERMISSIOM.SALESMAN.DELETE,
    PERMISSIOM.SALESMAN.DELETE_ALL,
    PERMISSIOM.USER.READ_SELF,
    PERMISSIOM.REMOTE.RECORD_IMPORT,
    PERMISSIOM.REMOTE.BONUS_SEND,
    PERMISSIOM.BONUS.GENERATE,
    PERMISSIOM.BONUS.VALIDATE_OR_REJECT_ALL,
    PERMISSIOM.RECORD.READ_ALL,
    PERMISSIOM.RECORD.SAVE_REMARKS,
    PERMISSIOM.USER.ADD,
    PERMISSIOM.USER.DELETE
  ],
};

exports.CEO = {
  name: "CEO",
  permissions: [
    PERMISSIOM.USER.READ_SELF,
    PERMISSIOM.REMOTE.RECORD_IMPORT,
    PERMISSIOM.REMOTE.BONUS_SEND,
    PERMISSIOM.BONUS.GENERATE,
    PERMISSIOM.BONUS.VALIDATE_OR_REJECT_ALL,
    PERMISSIOM.RECORD.READ_ALL,
    PERMISSIOM.RECORD.SAVE_REMARKS,
    PERMISSIOM.SOCIAL_PERFORMANCE.ADD,
    PERMISSIOM.SOCIAL_PERFORMANCE.DELETE,
    PERMISSIOM.SOCIAL_PERFORMANCE.DELETE_ALL
  ],
};

exports.HR = {
  name: "HR",
  permissions: [
    PERMISSIOM.USER.READ_SELF,
    PERMISSIOM.REMOTE.RECORD_IMPORT,
    PERMISSIOM.REMOTE.BONUS_SEND,
    PERMISSIOM.BONUS.VALIDATE_OR_REJECT_ALL,
    PERMISSIOM.RECORD.READ_ALL,
    PERMISSIOM.SOCIAL_PERFORMANCE.ADD,
    PERMISSIOM.SOCIAL_PERFORMANCE.DELETE,
    PERMISSIOM.SOCIAL_PERFORMANCE.DELETE_ALL
  ],
};

exports.SALESMAN = {
  name: "Salesman",
  permissions: [
    PERMISSIOM.USER.READ_SELF,
    PERMISSIOM.BONUS.VALIDATE_OR_REJECT_MINE,
    PERMISSIOM.RECORD.READ_MINE,
  ],
};
